version: '3'
services:
  postgresql:
    image: postgres:14.6
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - 5433:5432
  itmo_queue_bot:
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgresql
    ports:
      - 80:80