package tables

import (
	"fmt"
	"strings"
	"time"
)

// Users is table in DB
type Users struct {
	ID           int64     `gorm:"primaryKey;index;not null"`
	MyLang       string    `gorm:"default:es"`
	ToLang       string    `gorm:"default:zh"`
	Act          string    `gorm:"default:null"`
	Usings       int       `gorm:"default:0"`
	Blocked      bool      `gorm:"default:false"`
	LastActivity time.Time `gorm:"default:current_timestamp"`
	Lang         *string   `gorm:"default:null"`
	TTS          bool      `gorm:"default:true"`
}

func (u Users) Localize(key string, placeholders ...interface{}) string {
	key = strings.TrimSpace(key)
	localization := map[string]map[string]string{
		"Glad to see you again, %s": map[string]string{
			"en": "Glad to see you again, %s",
			"ru": "Рад видеть вас снова, %s",
			"uk": "Радий бачити вас знову, %s",
			"id": "Senang bertemu denganmu lagi, %s",
			"pt": "Fico feliz em vê-lo novamente, %s",
			"de": "Freut mich, dich wiederzusehen, %s",
			"es": "Me alegro de verte de nuevo, %s",
			"uz": "Sizni yana ko'rganimdan xursandman, %s",
			"it": "Sono felice di rivederti, %s",
			"ar": "سعيد برؤيتك مرة أخرى ،%s",
		},
		"начните вводить текст": map[string]string{
			"uk": "почніть вводити текст",
			"uz": "yozishni boshlang",
			"id": "mulai mengetik",
			"ar": "ابدأ الطباعة",
			"ru": "начните вводить текст",
			"de": "beginne zu tippen",
			"es": "empezar a escribir",
			"en": "start typing",
			"it": "iniziare a digitare",
			"pt": "começe a digitar",
		},

		"inline mode": map[string]string{
			"en": "🔎 inline mode",
			"ru": "🔎 инлайн режим",
			"es": "🔎 modo inline",
			"it": "🔎 modalità in linea",
			"ar": "🔎 الوضع المضمن",
			"de": "🔎 inline-modus",
			"uk": "🔎 инлайн режим",
			"uz": "🔎 Inline rejimi",
			"id": "🔎 inline mode",
			"pt": "🔎 inline modo",
		},
		"Choose language of the bot": map[string]string{
			"ar": "اختر لغة الروبوت",
			"en": "Choose language of the bot",
			"es": "Elige el idioma del bot",
			"uk": "Виберіть мову бота",
			"id": "Pilih bahasa bot",
			"it": "Scegli la lingua del bot",
			"ru": "Выберите язык бота",
			"de": "Wählen Sie die Sprache des Bots",
			"uz": "Bot tilini tanlang",
			"pt": "Escolha o idioma do bot",
		},
		"You translate from one language to the same language": map[string]string{
			"en": "You translate from one language to the same language",
			"de": "Sie übersetzen von einer Sprache in die gleiche Sprache",
			"pt": "Você traduz de um idioma para o mesmo idioma",
			"ru": "Вы переводите с одного языка на тот же язык",
			"es": "Traduces de un idioma al mismo idioma",
			"uk": "Ви перекладаєте з однієї мови на ту саму мову",
			"uz": "Siz bir tildan bir tilga tarjima qilasiz",
			"id": "Anda menerjemahkan dari satu bahasa ke bahasa yang sama",
			"it": "Traduci da una lingua alla stessa lingua",
			"ar": "أنت تترجم من لغة إلى نفس اللغة",
		},

		"set language of the bot": map[string]string{
			"it": "impostare la lingua del bot",
			"ar": "ضبط لغة الروبوت",
			"en": "set language of the bot",
			"ru": "установить язык бота",
			"es": "establecer el idioma del bot",
			"uz": "bot tilini o'rnating",
			"de": "Sprache des Bots einstellen",
			"uk": "встановити мову бота",
			"id": "atur bahasa bot",
			"pt": "definir idioma do bot",
		},
		"show keyboard": map[string]string{
			"id": "tampilkan papan ketik",
			"it": "mostra la tastiera",
			"ar": "تظهر لوحة المفاتيح",
			"es": "Mostrar teclado",
			"uk": "показати клавіатуру",
			"uz": "klaviaturani ko'rsatish",
			"pt": "mostrar teclado",
			"en": "show keyboard",
			"ru": "показать клавиатуру",
			"de": "Tastatur zeigen",
		},

		"the text you want to translate": map[string]string{
			"es": "el texto que quieres traducir",
			"uz": "siz tarjima qilmoqchi bo'lgan matn",
			"id": "teks yang ingin Anda terjemahkan",
			"pt": "o texto que você quer traduzir",
			"ar": "النص الذي تريد ترجمته",
			"en": "the text you want to translate",
			"de": "den Text, den Sie übersetzen möchten",
			"it": "il testo che vuoi tradurre",
			"ru": "текст, который ты хочешь перевести",
			"uk": "текст, який ти хочеш перекласти",
		},
		"Попробовать": map[string]string{
			"de": "Versuchen",
			"es": "tratar",
			"uk": "Спробувати",
			"uz": "harakat qilib ko'ring",
			"it": "Tentativo",
			"en": "Try it out",
			"id": "mencoba",
			"pt": "experimentar",
			"ar": "يحاول",
			"ru": "Попробовать",
		},
		"Did I translate it correctly?": map[string]string{
			"id": "Apakah saya menerjemahkannya dengan benar?",
			"it": "L'ho tradotto correttamente?",
			"de": "Habe ich es richtig übersetzt?",
			"es": "¿Lo traduje correctamente?",
			"en": "Did I translate it correctly?",
			"ar": "هل قمت بترجمتها بشكل صحيح؟",
			"pt": "Eu traduzi corretamente?",
			"ru": "Я правильно перевел?",
			"uk": "Чи правильно я переклав?",
			"uz": "Men uni to'g'ri tarjima qildimmi?",
		},
		"<i>Thank you for choosing our translator Translo</i>": map[string]string{
			"ru": "<i>Спасибо, что выбрали наш переводчик Трансло</i>",
			"uz": "<i>Translo tarjimonimizni tanlaganingiz uchun tashakkur</i>",
			"en": "<i>Thank you for choosing our translator Translo</i>",
			"uk": "<i>Дякую, що вибрали наш перекладач Трансло</i>",
			"it": "<i>Grazie per aver scelto il nostro traduttore Translo</i>",
			"de": "<i>Vielen Dank, dass Sie sich für unseren Übersetzer Translo entschieden haben</i>",
			"ar": "<i> شكرا لاختيارك مترجمنا Translo </i>",
			"id": "<i>Terima kasih telah memilih penerjemah kami, Translo</i>",
			"es": "<i>Gracias por elegir nuestro traductor Translo</i>",
			"pt": "<i>Obrigado por escolher nosso tradutor Translo</i>",
		},
		"Попытаюсь исправить...": map[string]string{
			"pt": "vou tentar consertar...",
			"id": "saya akan coba perbaiki...",
			"ru": "Попытаюсь исправить...",
			"ar": "سأحاول إصلاح ...",
			"uz": "Men tuzatishga harakat qilaman ...",
			"uk": "Спробую виправити...",
			"es": "intentaré arreglar...",
			"it": "cercherò di aggiustare...",
			"de": "Ich werde versuchen, es zu beheben ...",
			"en": "I'll try to fix...",
		},

		"Привет": map[string]string{
			"it": "Ciao",
			"uk": "Привіт",
			"de": "Hallo",
			"uz": "Salom",
			"ar": "أهلاً",
			"en": "Hi",
			"id": "Hai",
			"ru": "Привет",
			"pt": "Oi",
			"es": "Hola",
		},
		"Excuses": map[string]string{
			"en": "We are sorry that we were unable to translate your text. \nHere is a list of other translators while we fix ours: 👇\n\n@YTranslateBot\n@lingvo_ebot\n@multitran_bot\n\nWhen we fix the bug, we will write to you. It will be in 24-72h\n Best regards, Translo team",
			"uk": "Жаль, що нам не вдалося перекласти ваш текст. \nОсь вам список інших перекладачів, поки ми виправляємо наш: 👇\n\n@YTranslateBot\n@lingvo_ebot\n@multitran_bot\n\nКоли ми виправимо помилку, ми вам напишемо. Це буде через 24-72ч\nЗ повагою, команда Трансло",
			"uz": "Matningizni tarjima qila olmaganimizdan afsusdamiz. \nMana oʻzimiznikini tuzatayotgan boshqa tarjimonlar roʻyxati: 👇\n\n@YTranslateBot\n@lingvo_ebot\n@multitran_bot\n\nXatoni tuzatganimizda, biz quyidagi manzilga xat yozamiz. siz. 24-72 soat ichida bo'ladi\n Hurmat bilan, Translo jamoasi",
			"id": "Kami mohon maaf karena kami tidak dapat menerjemahkan teks Anda. \nBerikut adalah daftar penerjemah lain yang sedang kami perbaiki: 👇\n\n@YTranslateBot\n@lingvo_ebot\n@multitran_bot\n\nSaat kami memperbaiki bug, kami akan menulis ke Anda. Ini akan terjadi dalam 24-72 jam\n Salam, tim Translo",
			"it": "Siamo spiacenti di non essere riusciti a tradurre il tuo testo. \nEcco un elenco di altri traduttori mentre risolviamo il nostro: 👇\n\n@YTranslateBot\n@lingvo_ebot\n@multitran_bot\n\nQuando risolviamo il bug, scriveremo a voi. Sarà tra 24-72 ore\n Cordiali saluti, team Translo",
			"ru": "Сожалеем, что нам не удалось перевести ваш текст. \nВот вам список других переводчиков, пока мы исправляем наш: 👇\n\n@YTranslateBot\n@lingvo_ebot\n@multitran_bot\n\nКогда мы исправим ошибку, мы вам напишем. Это будет через 24-72ч\nС уважением, команда Трансло",
			"de": "Es tut uns leid, dass wir Ihren Text nicht übersetzen konnten. \nHier ist eine Liste mit anderen Übersetzern, während wir unsere reparieren: 👇\n\n@YTranslateBot\n@lingvo_ebot\n@multitran_bot\n\nWenn wir den Fehler behoben haben, schreiben wir an Sie. Es wird in 24-72 Stunden sein\n Mit freundlichen Grüßen, Translo-Team",
			"es": "Lamentamos no haber podido traducir su texto. \nAquí hay una lista de otros traductores mientras solucionamos el nuestro: 👇\n\n@YTranslateBot\n@lingvo_ebot\n@multitran_bot\n\nCuando solucionemos el error, escribiremos a tú. Será en 24-72h\n Saludos cordiales, Equipo Translo",
			"pt": "Lamentamos não poder traduzir seu texto. \nAqui está uma lista de outros tradutores enquanto corrigimos o nosso: 👇\n\n@YTranslateBot\n@lingvo_ebot\n@multitran_bot\n\nQuando corrigirmos o bug, escreveremos para vocês. Será em 24-72h\n Atenciosamente, equipe Translo",
			"ar": "نأسف لعدم تمكننا من ترجمة النص الخاص بك. \n فيما يلي قائمة بالمترجمين الآخرين أثناء قيامنا بإصلاح الخطأ لدينا: 👇 \n \nYTranslateBot \nlingvo_ebot \nmultitran_bot \n \n عندما نصلح الخطأ ، سنكتب إلى أنت. سيكون في 24-72h \n مع أطيب التحيات ، فريق Translo",
		},
		"С возвращением!": map[string]string{
			"de": "Willkommen zurück!",
			"uz": "Qaytganing bilan!",
			"it": "Ben tornato!",
			"en": "Welcome back!",
			"es": "¡Bienvenido de nuevo!",
			"uk": "З поверненням!",
			"id": "Selamat datang kembali!",
			"pt": "Bem vindo de volta!",
			"ar": "مرحبًا بعودتك!",
			"ru": "С возвращением!",
		},

		"Добро пожаловать. Мы рады, что вы снова с нами. ✋": map[string]string{
			"es": "Bienvenidos. Nos alegramos de que esté con nosotros de nuevo. ✋",
			"it": "Benvenuto. Siamo felici che tu sia di nuovo con noi. ✋",
			"ar": "أهلا بك. نحن سعداء لأنك معنا مرة أخرى. ✋",
			"pt": "Receber. Estamos felizes por você estar conosco novamente. ✋",
			"en": "Welcome. We are glad that you are with us again. ✋",
			"ru": "Добро пожаловать. Мы рады, что вы снова с нами. ✋",
			"de": "Willkommen zurück. Wir freuen uns, dass Sie wieder bei uns sind. ✋",
			"uk": "Ласкаво просимо. Ми раді, що ви знову з нами. ✋",
			"uz": "Xush kelibsiz. Yana biz bilan ekanligingizdan xursandmiz. ✋",
			"id": "Selamat datang. Kami senang Anda bersama kami lagi. ✋.",
		},
		"Порекомендовать бота": map[string]string{
			"de": "Empfehlen Sie einen Bot",
			"uk": "Рекомендувати робота",
			"it": "Consiglia un bot",
			"ar": "يوصي روبوت",
			"en": "Recommend a bot",
			"ru": "Порекомендовать бота",
			"es": "recomendar un bot",
			"uz": "Botni tavsiya eting",
			"id": "Rekomendasikan bot",
			"pt": "Recomende um bot",
		},
		"inline_ad": map[string]string{
			"de": "🔥 <a href=\"https://t.me/translobot\">Translo</a> 🌐 - beste in der Welt der bot-übersetzer in Telegram.",
			"uk": "🔥 <a href=\"https://t.me/translobot\">Translo</a> 🌐 - кращий в світі бот-перекладач в Telegram.",
			"id": "🔥 <a href=\"https://t.me/translobot\">Translo</a> 🌐 - terbaik di dunia bot penerjemah untuk Telegram.",
			"it": "🔥 <a href=\"https://t.me/translobot\">Translo</a> 🌐 - è la migliore al mondo bot-traduttore a Telegram.",
			"pt": "🔥 <a href=\"https://t.me/translobot\">Translo</a> 🌐 - o melhor do mundo bot-tradutor em Telegram.",
			"ar": "🔥 <a href=\"https://t.me/translobot\">Translo</a> 🌐 - العالم أفضل بوت مترجم برقية.",
			"en": "🔥 <a href=\"https://t.me/translobot\">Translo</a> 🌐 - the world's best bot translator for Telegram.",
			"ru": "🔥 <a href=\"https://t.me/translobot\">Translo</a>  🌐 - лучший в мире бот-переводчик в Telegram.",
			"es": "🔥 <a href=\"https://t.me/translobot\">Translo</a> 🌐 - mejor en el mundo de bots traductor en Telegram.",
			"uz": "🔥 <a href=\"https://t.me/translobot\">Translo</a> 🌐 - dunyodagi eng yaxshi telegram tarjimon boti",
		},
		"Translating...": map[string]string{
			"ru": "Перевожу...",
			"es": "Traductorio...",
			"en": "Translating...",
			"ar": "جار الترجمة...",
			"it": "Traduzione in corso...",
			"uk": "Переклад...",
			"pt": "Traduzindo...",
			"uz": "Tarjima qilinmoqda...",
			"id": "Menerjemahkan...",
			"de": "Übersetzen...",
		},
		"Something went wrong. Try again later or contact @armanokka if it's no trouble": map[string]string{
			"ru": "Что-то пошло не так. Повторите попытку позже или свяжитесь с @armanokka, если это не проблема",
			"ar": "هناك خطأ ما. حاول مرة أخرى لاحقًا أو تواصل معarmanokka إذا لم تكن هناك مشكلة",
			"en": "Something went wrong. Try again later or contact @armanokka if it's no trouble",
			"de": "Etwas ist schief gelaufen. Versuchen Sie es später noch einmal oder wenden Sie sich an @armanokka, wenn es keine Probleme gibt",
			"es": "Algo salió mal. Vuelve a intentarlo más tarde o ponte en contacto con @armanokka si no hay problema.",
			"uz": "Nimadir noto'g'ri bajarildi. Keyinroq qayta urinib ko‘ring yoki muammo bo‘lmasa, @armanokka bilan bog‘laning",
			"uk": "Щось пішло не так. Спробуйте пізніше або зв’яжіться з @armanokka, якщо це не проблема",
			"pt": "Algo deu errado. Tente novamente mais tarde ou entre em contato com @armanokka se não houver problemas",
			"id": "Ada yang salah. Coba lagi nanti atau hubungi @armanokka jika tidak ada masalah",
			"it": "Qualcosa è andato storto. Riprova più tardi o contatta @armanokka se non ci sono problemi",
		},

		"кликните, чтобы порекомендовать бота в чате": map[string]string{
			"es": "haga clic aquí para recomendar un bot de chat en vivo",
			"it": "cliccare per raccomandare un bot in chat",
			"en": "click to recommend the bot in the chat",
			"de": "klicken Sie, um zu empfehlen im Chat bot",
			"uz": "chatda botni tavsiya qilish uchun bosing",
			"id": "klik untuk merekomendasikan bot di chat",
			"pt": "clique para recomendar um bot no bate-papo",
			"ar": "انقر فوق أن يوصي بوت في الدردشة",
			"ru": "кликните, чтобы порекомендовать бота в чате",
			"uk": "натисніть, щоб порекомендувати бота в чаті",
		},
		"Озвучить": map[string]string{
			"uz": "Ovoz berish",
			"id": "Suara itu lebih dari",
			"it": "Esprimere",
			"pt": "Ouvir",
			"ar": "صوت أكثر",
			"en": "Voice it over",
			"ru": "Озвучить",
			"de": "Äußern",
			"es": "La voz de",
			"uk": "Озвучити",
		},
		"Примеры": map[string]string{
			"es": "Ejemplos",
			"uk": "Приклади",
			"it": "Esempi",
			"ar": "أمثلة",
			"ru": "Примеры",
			"de": "Beispiele",
			"id": "Contoh",
			"pt": "Exemplos",
			"en": "Examples",
			"uz": "Misollar",
		},
		"Переводы": map[string]string{
			"uk": "Переклади",
			"pt": "Transferências",
			"en": "Translations",
			"de": "Übersetzungen",
			"es": "Traducciones",
			"it": "Traduzioni",
			"ar": "نقل",
			"ru": "Переводы",
			"uz": "Tarjima",
			"id": "Transfer",
		},
		"Словарь": map[string]string{
			"uz": "Lug'at",
			"id": "Kamus",
			"pt": "Dicionário",
			"en": "Dictionary",
			"ru": "Словарь",
			"uk": "Словник",
			"ar": "القاموس",
			"de": "Wörterbuch",
			"es": "Diccionario",
			"it": "Dizionario",
		},
		"Твое сообщение и так на %s языке. Выбери другой язык, на который надо переводить": map[string]string{
			"ru": "Твое сообщение и так на %s языке. Выбери другой язык, на который надо переводить",
			"en": "Your message is already in %s language. Choose another language to translate into",
			"pt": "Sua mensagem já está no idioma %s. Escolha outro idioma para traduzir",
			"ar": "رسالتك باللغة٪ s بالفعل. اختر لغة أخرى للترجمة إليها",
			"uz": "Xabaringiz allaqachon %s tilida. Tarjima qilish uchun boshqa tilni tanlang",
			"es": "Su mensaje ya está en %s idioma. Elija otro idioma para traducir",
			"de": "Ihre Nachricht ist bereits in %s Sprache. Wählen Sie eine andere Sprache, in die übersetzt werden soll",
			"id": "Pesan Anda sudah dalam bahasa %s. Pilih bahasa lain untuk diterjemahkan",
			"uk": "Твоє повідомлення і так %s мовою. Вибери іншу мову, якою треба перекладати",
			"it": "Il tuo messaggio è già nella lingua %s. Scegli un'altra lingua in cui tradurre",
		},
		"Choose language": map[string]string{
			"it": "Scegli la lingua",
			"ru": "Выберите язык",
			"ar": "اختر اللغة",
			"pt": "Escolha o seu idioma",
			"id": "Pilih bahasa",
			"uz": "Tilni tanlang",
			"uk": "Виберіть мову",
			"de": "Sprache wählen",
			"es": "Elige lengua",
			"en": "Choose language",
		},
		"Клавиатура обновлена": map[string]string{
			"ru": "Клавиатура обновлена",
			"uz": "Klaviatura yangilandi",
			"ar": "تم تحديث لوحة المفاتيح",
			"it": "Tastiera aggiornata",
			"id": "Papan ketik diperbarui",
			"en": "Keyboard updated",
			"de": "Tastatur aktualisiert",
			"pt": "Teclado atualizado",
			"es": "Teclado actualizado",
			"uk": "Клавіатура оновлено",
		},

		"Я рекомендую @translobot": map[string]string{
			"en": "I recommend @translobot",
			"de": "Ich empfehle @translobot",
			"uk": "Я рекомендую @translobot",
			"id": "Saya merekomendasikan @translobot",
			"ar": "أوصي @translobot",
			"ru": "Я рекомендую @translobot",
			"es": "Recomiendo @translobot",
			"uz": "Kanallarning birortasi ham ushbu nashr bilan ulashmadi",
			"it": "Mi raccomando @translobot",
			"pt": "Eu recomendo @translobot",
		},
		"Рассказать про нас": map[string]string{
			"es": "Hablar sobre nosotros",
			"pt": "Falar sobre nós",
			"ar": "أخبرنا عنا",
			"en": "Tell us about us",
			"ru": "Рассказать про нас",
			"de": "Über uns erzählen",
			"uk": "Розповісти про нас",
			"uz": "Biz haqimizda aytib bering",
			"id": "Beritahu kami tentang kami",
			"it": "Parlare di noi",
		},
		"Понравился бот? 😎 Поделись с друзьями, нажав на кнопку": map[string]string{
			"ru": "Понравился бот? 😎 Поделись с друзьями, нажав на кнопку",
			"it": "Piaciuto il bot? 😎 Condividi con i tuoi amici, cliccando sul pulsante",
			"uz": "Bot kabi? 😎 Tugmasini bosib do'stlaringiz bilan baham ko'ring",
			"id": "Apakah anda suka bot? 😎 Berbagi dengan teman-teman anda dengan mengklik tombol",
			"pt": "Gostei do bot? 😎 Partilhe com os seus amigos, clicando no botão",
			"ar": "هل تحب الآلي ؟ 😎 مشاركتها مع أصدقائك عن طريق النقر على زر",
			"en": "Did you like the bot? 😎 Share with your friends by clicking on the button",
			"de": "Mochte ich den bot? 😎 Teilen Sie mit Ihren Freunden, indem Sie auf die Schaltfläche",
			"es": "Bien el bot? 😎 Comparte con tus amigos haciendo clic en el botón",
			"uk": "Сподобався бот? 😎 Поділіться з друзями, натиснувши на кнопку",
		},
		"Отправь текстовое сообщение, чтобы я его перевел": map[string]string{
			"uz": "Uni tarjima qilish uchun matnli xabar yuboring",
			"ar": "ترسل لي رسالة حتى استطيع ترجمته",
			"es": "Envía un mensaje de texto, para que lo tradujo",
			"uk": "Відправ текстове повідомлення, щоб я його переклав",
			"id": "Saya mengirim pesan teks sehingga saya dapat menerjemahkannya",
			"it": "Invia un messaggio di testo che ho tradotto",
			"pt": "Envie uma mensagem de texto para que eu o traduzi",
			"en": "Send me a text message so I can translate it",
			"ru": "Отправь текстовое сообщение, чтобы я его перевел",
			"de": "Sende eine Textnachricht, dass ich ihn übersetzt habe",
		},
		"Просто напиши мне текст, а я его переведу": map[string]string{
			"uk": "Просто напиши мені текст, а я його переведу",
			"uz": "Menga faqat matn yozing va uni tarjima qilaman",
			"pt": "Basta escrever-me um texto e eu traduzir",
			"ru": "Просто напиши мне текст, а я его переведу",
			"de": "Schreiben Sie mir einfach den Text, und ich werde",
			"es": "Simplemente me escribe el texto, y lo he transferir",
			"ar": "فقط اكتب لي رسالة وأنا سوف ترجمته",
			"en": "Just write me a text and I'll translate it",
			"id": "Hanya menulis saya sms dan saya akan menerjemahkannya",
			"it": "Mi scrivi il testo, e io lo traduco",
		},
		"%s не поддерживается": map[string]string{
			"de": "%s wird nicht unterstützt",
			"uk": "%s не підтримується",
			"id": "%s tidak didukung",
			"it": "%s non è supportato",
			"pt": "%s não é suportado",
			"ar": "%s غير معتمد",
			"en": "%s is not supported",
			"ru": "%s не поддерживается",
			"es": "%s no es compatible",
			"uz": "%s qo'llab-quvvatlanmaydi",
		},
		"start_info": map[string]string{
			"id": "Sekarang saya akan terjemahkan dari %s ke %s dan kembali lagi. Jika anda ingin mengubah bahasa, menulis /memulai\n\n\nMengirim saya pesan, dan saya akan menerjemahkannya",
			"ar": "الآن سوف تترجم من %s %s والعودة مرة أخرى. إذا كنت ترغب في تغيير لغة الكتابة /بدء\n\n\nأرسل لي رسالة وأنا سوف تترجم لهم",
			"ru": "Теперь я буду переводить с %s на %s и обратно. Если захочешь сменить языки, напишешь /start\n\n\nОтправляй мне сообщения, а я буду их переводить",
			"uz": "Endi %s dan %s va orqaga tarjima qilaman. Agar tillarni o'zgartirishni xohlasangiz, yozing / boshlang\n\n\nMenga xabar yuboring va men ularni tarjima qilaman",
			"it": "Ora ho intenzione di tradurre da %s a %s e indietro. Se vuoi cambiare le lingue, scrivi /start\n\n\nMi mandare messaggi, e io sarò loro di tradurre",
			"en": "Now I will translate from %s to %s and back again. If you want to change languages, write /start\n\n\nSend me messages, and I'll translate them",
			"pt": "Agora vou traduzir de %s para %s e volta. Se quiseres mudar de línguas, irmão /start\n\n\nОтправляй-me mensagens, e eu serei o seu traduzir",
			"uk": "Тепер я буду перекладати з %s на %s і назад. Якщо захочеш змінити мови, напишеш /start\n\n\nВідправляй мені повідомлення, а я буду їх переказувати",
			"es": "Ahora voy a traducir de %s a %s, y viceversa. Si quieres cambiar el idioma, escribas /start\n\n\nEnvía me un mensaje, y me voy a traducirlas",
			"de": "Jetzt werde ich das übersetzen von %s auf %s und wieder zurück. Wenn Sie möchten ändern die Sprachen, schreiben /start\n\n\nSenden Sie mir eine Nachricht, ich werden Sie zu übersetzen",
		},

		"не получилось перевести": map[string]string{
			"de": "hat nicht funktioniert übersetzen",
			"uk": "не вийшло перевести",
			"it": "non è riuscito a tradurre",
			"ar": "لم أستطع ترجمته",
			"en": "couldn't translate it",
			"es": "no pude traducir",
			"uz": "tarjima qila olmadi",
			"id": "tidak bisa menerjemahkannya",
			"pt": "não conseguimos traduzir",
			"ru": "не получилось перевести",
		},

		"Report a bug or suggest a feature": map[string]string{
			"en": "Report a bug or suggest a feature",
			"es": "Informar de un error o sugerir una característica",
			"uz": "Xato haqida xabar bering yoki xususiyatni taklif qiling",
			"ru": "Сообщите об ошибке или предложите функцию",
			"de": "Report a bug oder ein feature vorschlagen",
			"uk": "Повідомте про помилку або запропонуйте функцію",
			"id": "Melaporkan bug atau menyarankan fitur",
			"it": "Segnalare un bug o suggerire una funzione",
			"pt": "Comunicar um erro ou \" sugerir um recurso",
			"ar": "تقرير الشوائب أو اقتراح ميزة",
		},
		"translate": map[string]string{
			"tr":    "Çevirmek",
			"zh":    "翻译",
			"fr":    "Traduire",
			"nl":    "vertalen",
			"ja":    "翻訳",
			"es":    "traducir",
			"id":    "menerjemahkan",
			"en":    "translate",
			"ro":    "Traduceți",
			"ar":    "يترجم",
			"be":    "перакладаць",
			"zh-hk": "翻譯",
			"sk":    "preložiť",
			"zh-sg": "翻译",
			"sw":    "kutafsiri",
			"fi":    "Kääntää",
			"pt":    "traduzir",
			"ru":    "перевести",
			"sr":    "превести",
			"de":    "Übersetzen",
			"lv":    "tulkot",
			"zh-mo": "翻譯",
			"zh-tw": "翻譯",
			"lt":    "išversti",
			"zh-cn": "翻译",
			"hi":    "अनुवाद करना",
			"kk":    "аудару",
			"pl":    "Tłumaczyć",
			"bg":    "превеждам",
			"cs":    "přeložit",
			"da":    "Oversætte",
			"sl":    "prevesti",
			"et":    "tõlkida",
			"el":    "μεταφράζω",
			"hu":    "fordít",
			"it":    "tradurre",
		},
		"Detect language": map[string]string{
			"it": "Rileva lingua",
			"pt": "Detectar idioma",
			"ru": "Определить язык",
			"uk": "Визначити мову",
			"uz": "Tilni aniqlash",
			"id": "Mendeteksi bahasa",
			"en": "Detect language",
			"de": "Sprache erkennen",
			"es": "Detectar idioma",
			"ar": "اكتشاف اللغة",
		},

		"Завершить диалог": map[string]string{
			"ru": "Завершить диалог",
			"id": "Mengakhiri dialog",
			"pt": "Terminar a conversa",
			"en": "End the dialog",
			"de": "Dialog beenden",
			"es": "Completar un diálogo",
			"uk": "Завершити діалог",
			"uz": "Suhbatni yakunlang",
			"it": "Terminare il dialogo",
			"ar": "في نهاية الحوار",
		},
		"Язык определен": map[string]string{
			"es": "Idioma definido",
			"uk": "Мова визначена",
			"uz": "Til belgilangan",
			"ar": "تعريف اللغة",
			"ru": "Язык определен",
			"de": "Sprache definiert",
			"id": "Bahasa ditentukan",
			"it": "Lingua definita",
			"pt": "Idioma definido",
			"en": "Language defined",
		},
		"Диалог завершен": map[string]string{
			"it": "Conversazione",
			"pt": "A conversa terminou",
			"ar": "الحوار انتهى",
			"en": "The dialog is finished",
			"ru": "Диалог завершен",
			"de": "Dialog abgeschlossen",
			"es": "La conversación ha finalizado",
			"uk": "Діалог завершено",
			"uz": "Muloqot yakunlandi",
			"id": "Dialog selesai",
		},
		"Как переводить еще удобнее": map[string]string{
			"es": "Cómo traducir aún mejor",
			"uk": "Як перекладати ще зручніше",
			"id": "Bagaimana menerjemahkan bahkan lebih nyaman",
			"it": "Come tradurre ancora più conveniente",
			"pt": "Como traduzir ainda mais",
			"ar": "كيفية ترجمة أكثر سهولة",
			"de": "Wie übersetzt man noch bequemer",
			"ru": "Как переводить еще удобнее",
			"uz": "Tarjima qilish yanada qulayroq",
			"en": "How to translate even more conveniently",
		},
		"пример текста": map[string]string{
			"es": "texto de ejemplo",
			"uk": "приклад тексту",
			"uz": "matn namunasi",
			"ru": "пример текста",
			"de": "Beispieltext",
			"id": "contoh teks",
			"it": "esempio di testo",
			"pt": "texto de exemplo",
			"ar": "النص عينة",
			"en": "sample text",
		},
		"Как переводить сообщения, не выходя из чата": map[string]string{
			"ru": "Как переводить сообщения, не выходя из чата",
			"de": "Wie übersetzt man Nachrichten, ohne aus dem Chat",
			"es": "Cómo traducir un mensaje sin salir de chat",
			"uk": "Як переводити повідомлення, не виходячи з чату",
			"it": "Come tradurre i messaggi, non lasciare la chat",
			"en": "How to translate messages without leaving the chat",
			"uz": "Suhbatdan chiqmasdan xabarlarni qanday tarjima qilish kerak",
			"id": "Bagaimana menerjemahkan pesan tanpa meninggalkan obrolan",
			"pt": "Como traduzir as mensagens sem sair do chat",
			"ar": "كيفية ترجمة الرسائل دون ترك الدردشة",
		},
		"Вас устраивает этот перевод?": map[string]string{
			"uz": "Ushbu tarjimadan qoniqasizmi?",
			"ru": "Вас устраивает этот перевод?",
			"it": "Siete soddisfatti di questa traduzione?",
			"en": "Are you satisfied with this translation?",
			"uk": "Вас влаштовує цей переклад?",
			"ar": "هل أنت راض عن هذه الترجمة ؟ ",
			"de": "Sie ordnet diese übersetzung?",
			"pt": "Você está satisfeito com esta tradução?",
			"es": "Usted satisfecho con esta traducción?",
			"id": "Apakah anda puas dengan terjemahan ini?",
		},
		"Мы учли ваш голос\nВаши отзывы помогут нам улучшить сервис": map[string]string{
			"ru": "Мы учли ваш голос\nВаши отзывы помогут нам улучшить сервис",
			"it": "Abbiamo preso in considerazione la tua voce\nI vostri commenti ci aiuteranno a migliorare il servizio",
			"de": "Wir berücksichtigen Ihre Stimme\nIhre Rückmeldungen helfen uns, den Service zu verbessern",
			"ar": "أخذنا التصويت بعين الاعتبار\nملاحظاتك سوف تساعدنا في تحسين الخدمة",
			"uk": "Ми врахували ваш голос\nВаші відгуки допоможуть нам поліпшити сервіс",
			"uz": "Sizning ovozingizni hisobga oldik\nSizning fikringiz xizmatni yaxshilashga yordam beradi",
			"en": "We took your vote into account\nYour feedback will help us improve the service",
			"es": "Hemos tenido en cuenta su voz\nSus comentarios nos ayudarán a mejorar el servicio",
			"id": "Kami mengambil suara anda ke rekening\nTanggapan anda akan membantu kami meningkatkan layanan",
			"pt": "Nós levamos em consideração a sua voz\nOs seus comentários ajudam-nos a melhorar o serviço",
		},
		"Спасибо!": map[string]string{
			"id": "Terima kasih!!!",
			"en": "Thanks!",
			"es": "Gracias!",
			"pt": "Obrigado!",
			"it": "Grazie!",
			"ar": "وذلك بفضل!",
			"de": "Danke!",
			"uz": "Rahmat!",
			"ru": "Спасибо!",
			"uk": "Спасибі!",
		},
		"Время ожидания жалобы на перевод истекло. Переведите сообщение еще раз": map[string]string{
			"id": "Waktu tunggu untuk transfer keluhan telah berakhir. Menerjemahkan pesan lagi",
			"de": "Die Wartezeit auf Beschwerde übersetzungen abgelaufen ist. Übersetzen Sie die Nachricht erneut",
			"it": "Il tempo di attesa reclami sulla traduzione è scaduto. Portare il messaggio ancora una volta",
			"ar": "وقت الانتظار لنقل الشكوى قد انتهت. ترجمة الرسالة مرة أخرى",
			"uz": "Transfer haqidagi shikoyatni kutish muddati tugadi. Xabarni qayta tarjima qiling",
			"pt": "O tempo de espera reclamações de tradução expirou. Coloque novamente a mensagem",
			"ru": "Время ожидания жалобы на перевод истекло. Переведите сообщение еще раз",
			"en": "The waiting time for a transfer complaint has expired. Translate the message again",
			"uk": "Час очікування скарги на переклад минув. Перекажіть повідомлення ще раз",
			"es": "El tiempo de espera de la queja en la traducción agotado. Ponga de nuevo el mensaje",
		},
		"turn text-to-speech off": map[string]string{
			"it": "disattivare la sintesi vocale",
			"pt": "desative a conversão de texto em fala",
			"ar": "إيقاف تحويل النص إلى كلام",
			"ru": "отключить преобразование текста в речь",
			"uk": "вимкнути перетворення тексту в мовлення",
			"uz": "matndan nutqqa oʻchirish",
			"id": "matikan text-to-speech",
			"en": "turn text-to-speech off",
			"de": "schalten Sie Text-zu-Sprache aus",
			"es": "desactivar texto a voz",
		},
		"Бот будет озвучивать переводы": map[string]string{
			"en": "The bot will voice translations 🔈✅",
			"de": "Der Bot spricht Übersetzungen 🔈✅",
			"it": "Il bot eseguirà le traduzioni vocali 🔈✅",
			"pt": "O bot fará traduções de voz 🔈✅",
			"id": "Bot akan menyuarakan terjemahan",
			"ar": "سيقوم الروبوت بصوت الترجمات 🔈✅",
			"ru": "Бот будет озвучивать переводы 🔈✅",
			"es": "El bot expresará las traducciones 🔈✅",
			"uk": "Бот озвучуватиме переклади 🔈✅",
			"uz": "Bot ovozli tarjimalarni amalga oshiradi 🔈✅",
		},

		"Бот больше не будет озвучивать переводы": map[string]string{
			"it": "Il bot non eseguirà più traduzioni vocali 🔇❌",
			"pt": "O bot não fará mais traduções de voz 🔇❌",
			"en": "The bot will no longer voice translations 🔇❌",
			"ru": "Бот больше не будет озвучивать переводы 🔇❌",
			"uz": "Bot boshqa ovozli tarjimalarni amalga oshirmaydi 🔇❌",
			"id": "Bot tidak akan lagi menyuarakan terjemahan",
			"ar": "لن يصدر الروبوت صوتًا بعد الآن للترجمات 🔇❌",
			"de": "Der Bot spricht keine Übersetzungen mehr 🔇❌",
			"es": "El bot ya no expresará las traducciones 🔇❌",
			"uk": "Бот більше не озвучуватиме переклади 🔇❌",
		},
		"turn text-to-speech on": map[string]string{
			"en": "turn text-to-speech on",
			"de": "Text-zu-Sprache einschalten",
			"es": "activar texto a voz",
			"id": "aktifkan text-to-speech",
			"ru": "включить преобразование текста в речь",
			"uk": "увімкніть перетворення тексту в мовлення",
			"uz": "matndan nutqqa funksiyasini yoqing",
			"it": "attiva la sintesi vocale",
			"pt": "ativar conversão de texto em fala",
			"ar": "تشغيل تحويل النص إلى كلام",
		},

		"tap on translation to send it": map[string]string{
			"en": "tap on translation to send it",
			"es": "toca la traducción para enviarla",
			"uk": "торкніться перекладу, щоб надіслати його",
			"uz": "yuborish uchun tarjima ustiga bosing",
			"ru": "нажмите на перевод, чтобы отправить его",
			"de": "Tippen Sie auf Übersetzung, um sie zu senden",
			"id": "ketuk terjemahan untuk mengirimnya",
			"it": "tocca la traduzione per inviarla",
			"pt": "toque na tradução para enviá-la",
			"ar": "اضغط على الترجمة لإرسالها",
		},
		"<b>Пожалуйста, не флудите!</b> Подождите 3 секунды после каждого запроса": map[string]string{
			"uz": "<b>Iltimos, suv bosmang!</b> Har bir soʻrovdan keyin 3 soniya kuting",
			"ar": "<b> من فضلك لا تفيض! </ b> انتظر 3 ثوان بعد كل طلب",
			"en": "<b>Please don't flood!</b> Wait 3 seconds after each request",
			"de": "<b>Bitte nicht überfluten!</b> Warten Sie nach jeder Anfrage 3 Sekunden",
			"es": "<b>¡Por favor, no inunde!</b> Espere 3 segundos después de cada solicitud",
			"uk": "<b>Будь ласка, не флудіть!</b> Зачекайте 3 секунди після кожного запиту",
			"id": "<b>Tolong jangan banjir!</b> Tunggu 3 detik setelah setiap permintaan",
			"it": "<b>Per favore, non inondare!</b> Attendi 3 secondi dopo ogni richiesta",
			"pt": "<b>Não faça flood!</b> Aguarde 3 segundos após cada solicitação",
			"ru": "<b>Пожалуйста, не флудите!</b> Подождите 3 секунды после каждого запроса",
		},

		"format_translation_tip": map[string]string{
			"es": "💡Sugerencia:\nSólo Translo puede traducir estos textos con formato, como: \"𝑴𝒓 𝒑𝒂𝒖𝒍𝒔𝒐𝒏 𝑷𝒊𝒆𝒕𝒆𝒓\"\nNi google, ni yahoo! ni ningún otro traductor porque no pueden. Pruebe y compruebe en este",
			"id": "💡Petunjuk:\nHanya Translo dapat menerjemahkan diformat teks-teks seperti: \"𝑴𝒓 𝒑𝒂𝒖𝒍𝒔𝒐𝒏 𝑷𝒊𝒆𝒕𝒆𝒓\"\nGoogle atau Yandex, atau translator tidak bisa melakukan itu. Mencobanya dan melihat untuk diri sendiri",
			"en": "💡Hint:\nOnly Translo can translate formatted texts such as: \"𝑴𝒓 𝒑𝒂𝒖𝒍𝒔𝒐𝒏 𝑷𝒊𝒆𝒕𝒆𝒓\"\nAny Google or Yandex, or any other translator can't do that. Try it out and see for yourself",
			"de": "💡Tipp:\nNur Translo übersetzen kann diese formatierte Texte, wie: \"𝑴𝒓 𝒑𝒂𝒖𝒍𝒔𝒐𝒏 𝑷𝒊𝒆𝒕𝒆𝒓\"\nWeder Google, Yandex, noch irgendein anderer übersetzer nicht so können. Probieren Sie es aus und überzeugen Sie sich",
			"uk": "💡Підказка:\nТільки Translo може переводити такі форматовані тексти, як: \"𝑴𝒓 𝒑𝒂𝒖𝒍𝒔𝒐𝒏 𝑷𝒊𝒆𝒕𝒆𝒓\"\nНі гугл, ні яндекс, ні будь-який інший перекладач так не можуть. Спробуйте і переконаєтеся в цьому",
			"pt": "💡Dica:\nSó Translo pode traduzir tais textos formatados, como: \"𝑴𝒓 𝒑𝒂𝒖𝒍𝒔𝒐𝒏 𝑷𝒊𝒆𝒕𝒆𝒓\"\nNem o google, nem ela, nem qualquer outro tradutor não podem. Tente e certifique-se neste",
			"it": "💡Suggerimento:\nSolo Translo in grado di tradurre i testi formattati, come: \"𝑴𝒓 𝒑𝒂𝒖𝒍𝒔𝒐𝒏 𝑷𝒊𝒆𝒕𝒆𝒓\"\nNé google, né yandex, né qualsiasi altro traduttore non possono. Provare e vedere di",
			"uz": "Подсказ uchi:\nFaqat Translo quyidagi formatlangan matnlarni tarjima qilishi mumkin: \"𝑴𝒓 𝒑𝒂𝒖𝒍𝒔𝒐𝒏 𝑷𝒊𝒆𝒕𝒆𝒓\"\nNa Google, na Yandex, na boshqa tarjimon ham shunday qila olmaydi. Uni sinab ko'ring va ishonch hosil qiling",
			"ru": "💡Подсказка:\nТолько Translo может переводить такие форматированные тексты, как: \"𝑴𝒓 𝒑𝒂𝒖𝒍𝒔𝒐𝒏 𝑷𝒊𝒆𝒕𝒆𝒓\"\nНи гугл, ни яндекс, ни любой другой переводчик так не могут. Попробуйте и убедитесь в этом",
			"ar": "💡تلميح:\nفقط Translo يمكن أن تترجم تنسيق النصوص مثل: \"𝑴𝒓 𝒑𝒂𝒖𝒍𝒔𝒐𝒏 𝑷𝒊𝒆𝒕𝒆𝒓\"\nأي جوجل أو ياندكس ، أو أي مترجم لا تستطيع أن تفعل ذلك. محاولة وانظر لنفسك",
		},
		"<b>Send text</b>, and bot will translate it": map[string]string{
			"es": "<b>Envía texto</b> y el bot lo traducirá",
			"uk": "<b>Надішліть текст</b>, і бот його перекладе",
			"uz": "<b>Matn yuboring</b> va bot uni tarjima qiladi",
			"id": "<b>Kirim teks</b>, dan bot akan menerjemahkannya",
			"pt": "<b>Enviar texto</b> e o bot irá traduzi-lo",
			"en": "<b>Send text</b>, and bot will translate it",
			"ru": "<b>Отправьте текст</b>, и бот его переведет",
			"ar": "<b> أرسل نصًا </ b> ، وسيقوم برنامج التتبُّع بترجمته",
			"de": "<b>Senden Sie Text</b> und der Bot übersetzt ihn",
			"it": "<b>Invia testo</b> e il bot lo tradurrà",
		},

		"Переведено с %s": map[string]string{
			"de": "Übersetzt von %s",
			"ar": "مترجمة من٪ %s",
			"es": "Traducido de %s",
			"ru": "Переведено с %s",
			"pt": "Traduzido de %s",
			"uk": "Перекладено з %s",
			"en": "Translated from %s",
			"id": "Diterjemahkan dari %s",
			"it": "Tradotto da %s",
			"uz": "%s dan tarjima qilingan",
		},
		"text": map[string]string{
			"ru": "текст",
			"es": "texto",
			"uz": "matn",
			"pt": "texto",
			"ar": "نص",
			"de": "Text",
			"it": "testo",
			"uk": "текст",
			"id": "teks",
			"en": "text",
		},
		"Text to translate...": map[string]string{
			"uz": "Tarjima uchun matn...",
			"it": "Testo da tradurre...",
			"pt": "Texto para traduzir...",
			"ar": "نص للترجمة ...",
			"en": "Text to translate...",
			"ru": "Текст для перевода...",
			"de": "Zu übersetzender Text...",
			"es": "Texto a traducir...",
			"uk": "Текст для перекладу...",
			"id": "Teks untuk diterjemahkan...",
		},
	}
	if u.Lang == nil {
		en := "en"
		u.Lang = &en
	}

	if v, ok := localization[key]; ok {
		if v, ok := v[*u.Lang]; ok {
			return fmt.Sprintf(v, placeholders...)
		}
		return key + "\nLOCALIZATION_KEY_NOT_FOUND"
	}
	return key + "\nLOCALIZATION_NOT_FOUND"
}

type Mailing struct {
	ID int64 // fk users.id
}

func (Mailing) TableName() string {
	return "mailing"
}
