package bot

import (
    "fmt"
    "strings"
)


var commandTranslations = map[string][]string{
    "my language": {
        "mi idioma",
        "bahasaku",
        "my language",
        "mening tilim",
        "meine sprache",
        "minha língua",
        "mio linguaggio",
        "мой язык",
        "моя мова",
    },
    "translate language": {
        "translate language",
        "sprache übersetzen",
        "traducir idioma",
        "terjemahkan bahasa",
        "traduzir idioma",
        "tilni tarjima qilish",
        "язык перевода",
        "мова перекладу",
        "traduzir linguagem",
        "traduci lingua",
    },
}



var translations = map[string]map[string]string{
    "Bot language": {
        "it": "Linguaggio Bot",
        "de": "Bot-Sprache",
        "es": "Lenguaje bot",
        "pt": "Linguagem de bot",
        "id": "Bahasa bot",
        "uk": "Бот-мова",
        "uz": "Bot tili",
        "ru": "Язык бота",
    },
    "Too big text": {
        "id": "Teks terlalu besar",
        "it": "Testo troppo grande",
        "uz": "Juda katta matn",
        "de": "Zu großer Text",
        "ru": "Слишком большой текст",
        "es": "Texto demasiado grande",
        "uk": "Занадто великий текст",
        "pt": "Texto muito grande",
        "en": "Too big text",
    },
    "Available only for idioms, nouns, verbs and adjectives": {
        "es": "Disponible solo para modismos, sustantivos, verbos y adjetivos",
        "pt": "Disponível apenas para expressões idiomáticas, substantivos, verbos e adjetivos",
        "it": "Disponibile solo per modi di dire, nomi, verbi e aggettivi",
        "uz": "Faqat iboralar, otlar, fe'llar va sifatlar uchun mavjud",
        "de": "Nur für Redewendungen, Substantive, Verben und Adjektive verfügbar",
        "ru": "Доступно только для идиом, существительных, глаголов и прилагательных.",
        "en": "Available only for idioms, nouns, verbs and adjectives",
        "uk": "Доступно лише для ідіом, іменників, дієслів та прикметників",
        "id": "Hanya tersedia untuk idiom, kata benda, kata kerja dan kata sifat",
    },
    "Sorry, error caused.\n\nPlease, don't block the bot, I'll fix the bug in near future, the administrator has already been warned about this error ;)": {
        "es": "Lo sentimos, error causado.\n\nPor favor, no bloquees el bot, corregiré el error en un futuro cercano, el administrador ya ha sido advertido sobre este error ;)",
        "uk": "Вибачте, сталася помилка.\n\nБудь ласка, не блокуйте бота, я виправлю помилку найближчим часом, адміністратор вже попереджений про цю помилку ;)",
        "pt": "Desculpa, erro causado.\n\nPor favor, não bloqueie o bot, eu vou corrigir o bug em um futuro próximo, o administrador já foi avisado sobre este ",
        "id": "Maaf, kesalahan disebabkan.\n\nTolong, jangan halangi robot itu, aku akan memperbaiki bug dalam waktu dekat, administrator telah diperingatkan tentang kesalahan ini ;)",
        "it": "Scusa, errore causato.\n\nPer favore, non bloccare il bot, correggerò il bug nel prossimo futuro, l'amministratore è già stato avvertito di questo errore;)",
        "uz": "Uzr, xato sabab.\n\nIltimos, botni bloklamang, yaqin kelajakda xatoni tuzataman, administrator bu xato haqida allaqachon ogohlantirilgan ;)",
        "de": "Sorry, Fehler verursacht.\n\nBitte blockieren Sie den Bot nicht, ich werde den Fehler in naher Zukunft beheben, der Administrator wurde bereits vor diesem Fehler gewarnt ;)",
        "ru": "Извините, произошла ошибка.\n\nПожалуйста, не блокируйте бота, я исправлю ошибку в ближайшее время, администратор уже предупрежден об этой ошибке ;)",
    },
    "Delete": {
        "id": "Menghapus",
        "it": "Elimina",
        "ru": "Удалить",
        "uz": "O'chirish",
        "pt": "Excluir",
        "es": "Borrar",
        "en": "Delete",
        "de": "Löschen",
        "uk": "Видалити",
    },
    "Now your language is %s": {
        "es": "Ahora tu idioma es %s",
        "it": "Ora la tua lingua è %s",
        "uk": "Тепер ваша мова - %s",
        "ru": "Теперь ваш язык %s",
        "uz": "Endi sizning tilingiz - %s",
        "en": "Now your language is %s",
        "de": "Ihre Sprache ist jetzt %s",
        "id": "Sekarang bahasa Anda adalah %s",
        "pt": "Agora seu idioma é %s",
    },
    "Другие языки": {
        "uz": "Boshqa tillar",
        "en": "Other languages",
        "ru": "Другие языки",
        "es": "Otros idiomas",
        "id": "Bahasa lainnya",
        "it": "Altre lingue",
        "pt": "Outras línguas",
        "uk": "Інші мови",
        "de": "Andere Sprachen",
    },
    "⏳ Translating...": {
        "ru": "⏳ Перевожу...",
        "es": "⏳ Traducir...",
        "uk": "⏳ Перекласти...",
        "pt": "⏳ Traduzir...",
        "id": "⏳ Terjemahkan...",
        "it": "⏳ Traduci...",
        "uz": "⏳ Tarjima qilish...",
        "de": "⏳ Übersetzen...",
    },
    "Variants": {
        "it": "varianti",
        "pt": "Variantes",
        "ru": "Варианты",
        "uk": "Варіанти",
        "uz": "Variantlar",
        "de": "Varianten",
        "es": "Variantes",
        "id": "Varian",
    },
    "/start": {
        "ru": "<b>1.</b> Установите свой язык и язык перевода с помощью кнопок внизу.\n<b>2.</b> Отправляйте мне текст и я его переведу",
        "uk": "<b>1.</b> Встановіть мову та мову перекладу за допомогою кнопок внизу.\n <b>2.</b> Надсилайте мені текст і я його переведу",
        "it": "<b>1.</b> Imposta la tua lingua e la lingua di destinazione utilizzando i pulsanti in basso.\n <b>2.</b> Mandami il testo e lo traduco",
        "pt": "<b>1.</b> Defina seu idioma e idioma de chegada usando os botões abaixo.\n <b>2.</b> Envie-me o texto e eu irei traduzi-lo",
        "en": "<b>1.</b> Set your language and target language using the buttons below.\n <b>2.</b> Send me the text and I will translate it",
        "de": "<b>1.</b> Stellen Sie Ihre Sprache und Zielsprache über die Schaltflächen unten ein.\n <b>2.</b> Senden Sie mir den Text und ich übersetze ihn",
        "es": "<b>1.</b> Configure su idioma y el idioma de destino usando los botones a continuación.\n <b>2.</b> Envíame el texto y lo traduciré",
        "uz": "<b>1.</b> Quyidagi tugmalar yordamida til va maqsad tilingizni sozlang.\n <b>2.</b> Matnni menga yuboring, men uni tarjima qilaman",
        "id": "<b>1.</b> Atur bahasa dan bahasa target Anda menggunakan tombol di bawah ini.\n <b>2.</b> Kirimi saya teks dan saya akan menerjemahkannya",
    },
    "Unsupported language or internal error": {
        "pt": "Idioma não suportado ou erro interno",
        "id": "Bahasa yang tidak didukung atau kesalahan internal",
        "it": "Lingua non supportata o errore interno",
        "uz": "Qo'llab-quvvatlanmaydigan til yoki ichki xato",
        "de": "Nicht unterstützte Sprache oder interner Fehler",
        "ru": "Неподдерживаемый язык или внутренняя ошибка",
        "es": "Idioma no admitido o error interno",
        "uk": "Непідтримувана мова або внутрішня помилка",
    },
    "Please, send text message": {
        "it": "Per favore, invia un messaggio di testo",
        "uz": "Iltimos, SMS yuboring",
        "de": "Bitte SMS senden",
        "ru": "Пожалуйста, отправьте текстовое сообщение",
        "es": "Por favor, envíe un mensaje de texto",
        "uk": "Будь ласка, надішліть текстове повідомлення",
        "pt": "Por favor, envie mensagem de texto",
        "id": "Tolong, kirim pesan teks",
    },
    "bot_advertise":{
        "es": "Estaremos agradecidos si les cuenta a sus amigos sobre nosotros. Reenvíeles este mensaje. <b>Translo Bot</b> Traductor en línea rápido y conveniente <i>Admite 182</i> <b>(!)</b> <i>Idiomas</i> @translobot",
        "uk": "We will be grateful if you tell your friends about us. Forward them this message. <b>Translo Bot</b> Fast and convenient inline translator <i>Supports 182</i> <b>(!)</b> <i>Languages</i> @translobot",
        "pt": "Ficaremos gratos se você contar a seus amigos sobre nós. Encaminhe esta mensagem para eles. <b>Translo Bot Conversor</b> embutido rápido e conveniente <i>Suporta 182</i> <b>(!)</b> <i>Idiomas</i> @translobot",
        "en": "We will be grateful if you tell your friends about us. Forward them this message. <b>Translo Bot</b> Fast and convenient inline translator <i>Supports 182</i> <b>(!)</b> <i>Languages</i> @translobot",
        "it": "Ti saremo grati se parlerai di noi ai tuoi amici. Inoltra loro questo messaggio. <b>Translo Bot</b> Traduttore in linea veloce e conveniente <i>Supporta 182</i> <b>(!)</b> <i>Lingue</i> @translobot",
        "uz": "Agar do&#39;stlaringizga biz haqimizda aytib bersangiz, minnatdor bo&#39;lamiz. Bu xabarni ularga yuboring. <b>Translo Bot</b> Tez va qulay inline tarjimon <i>182</i> <b>(!)</b> <i>Tilni</i> <i>qo&#39;llab -quvvatlaydi</i> @translobot",
        "de": "Wir sind Ihnen dankbar, wenn Sie Ihren Freunden von uns erzählen. Leiten Sie diese Nachricht weiter. <b>Translo Bot</b> Schneller und bequemer Inline-Übersetzer <i>Unterstützt 182</i> <b>(!)</b> <i>Sprachen</i> @translobot",
        "ru": "We will be grateful if you tell your friends about us. Forward them this message.\n\n<b>Translo Bot</b> Fast and convenient inline translator\n<i>Supports 182</i> <b>(!)</b> <i>languages</i>\n\n@translobot",
        "id": "Kami akan berterima kasih jika Anda memberi tahu teman Anda tentang kami. Teruskan pesan ini kepada mereka. <b>Translo Bot</b> Penerjemah sebaris yang cepat dan nyaman <i>Mendukung 182</i> <b>(!)</b> <i>Bahasa</i> @translobot",
    },
    "bot_advertise_without_html_tags": {
        "en": "Translo Bot Fast and convenient inline translator Supports 182 (!) Languages \n\n@translobot",
        "uk": "Translo Bot Швидкий і зручний інлайн перекладач Підтримує 182 (!) Мови @translobot",
        "id": "Translo Bot Penerjemah sebaris yang cepat dan nyaman Mendukung 182 (!) Bahasa @translobot",
        "pt": "Translo Bot Conversor embutido rápido e conveniente Suporta 182 (!) Idiomas @translobot",
        "it": "Translo Bot Traduttore in linea veloce e conveniente Supporta 182 (!) Lingue @translobot",
        "uz": "Translo Bot Tez va qulay inline tarjimon 182 (!) Tilni qo&#39;llab -quvvatlaydi @translobot",
        "de": "Translo Bot Schneller und bequemer Inline-Übersetzer Unterstützt 182 (!) Sprachen @translobot",
        "ru": "Translo Bot\nБыстрый и удобный инлайн переводчик \nПоддерживает 182(!) языка\n\n@translobot",
        "es": "Translo Bot Traductor en línea rápido y conveniente Admite 182 (!) Idiomas @translobot",
    },
    "Share": {
        "de": "Teilen",
        "ru": "Поделиться",
        "es": "Cuota",
        "id": "Membagikan",
        "en": "Share",
        "it": "Condividere",
        "uz": "Ulashing",
        "uk": "Поділитися",
        "pt": "Compartilhado",
    },
    "My Language": {
        "ru": "Мой язык",
        "es": "Mi idioma",
        "pt": "Minha língua",
        "en": "My Language",
        "it": "Mio linguaggio",
        "uz": "Mening tilim",
        "de": "Meine Sprache",
        "uk": "Моя мова",
        "id": "Bahasaku",
    },
    "Now translate language is %s": {
        "en": "Now translate language is %s",
        "de": "Die Übersetzungssprache ist jetzt %s",
        "id": "Sekarang bahasa terjemahan adalah %s",
        "it": "Ora la lingua di traduzione è %s",
        "pt": "Agora o idioma de tradução é %s",
        "ru": "Теперь язык перевода %s",
        "uz": "Endi tarjima tili - %s",
        "es": "Ahora el idioma de traducción es %s",
        "uk": "Тепер мовою перекладу є %s",
    },
    "Выберите свой язык": {
        "en": "Choose your language",
        "ru": "Выберите свой язык",
        "es": "Elige tu idioma",
        "id": "Pilih bahasamu",
        "pt": "Escolha seu idioma",
        "de": "Wähle deine Sprache",
        "uk": "Виберіть свою мову",
        "uz": "Tilingizni tanlang",
        "it": "scegli la tua LINGUA",
    },
    "Error, sorry.": {
        "pt": "Erro, desculpe.",
        "id": "Kesalahan, maaf.",
        "it": "Errore, scusa.",
        "uz": "Xato, uzr.",
        "de": "Fehler, tut mir leid.",
        "ru": "Ошибка, извините.",
        "es": "Error, lo siento.",
        "uk": "Помилка, вибачте.",
    },
    "Ok, close": {
        "uz": "Yaxshi, yaqin",
        "de": "Okay, nah",
        "ru": "Хорошо, закрыть",
        "es": "Ok cerrar",
        "pt": "Ok fechar",
        "id": "Oke, tutup",
        "uk": "Гаразд, близько",
        "it": "Ok, chiudi",
    },
    "Выберите страны пользователей, которые получат вашу рассылку. Когда закончите, нажмите кнопку Далее": {
        "id": "Pilih negara pengguna yang akan menerima buletin Anda. Setelah selesai, klik Berikutnya",
        "it": "Seleziona i paesi degli utenti che riceveranno la tua newsletter. Al termine, fai clic su Avanti",
        "pt": "Selecione os países dos usuários que receberão sua newsletter. Quando terminar, clique em Avançar",
        "ru": "Выберите страны пользователей, которые получат вашу рассылку. Когда закончите, нажмите кнопку Далее",
        "de": "Wählen Sie die Länder der Benutzer aus, die Ihren Newsletter erhalten. Wenn Sie fertig sind, klicken Sie auf Weiter",
        "es": "Seleccione los países de los usuarios que recibirán su newsletter. Cuando termine, haga clic en Siguiente",
        "uk": "Виберіть країни користувачів, які отримають вашу розсилку. Коли закінчите, натисніть кнопку Далі",
        "uz": "Sizning axborot byulleteningizni oladigan foydalanuvchilarning mamlakatlarini tanlang. Ish tugagach, Keyingiga bosing",
        "en": "Select the countries of the users who will receive your newsletter. When done, click Next",
    },
    "Empty result": {
        "pt": "Resultado vazio",
        "id": "Hasil kosong",
        "it": "Risultato vuoto",
        "uz": "Bo'sh natija",
        "de": "Leeres Ergebnis",
        "ru": "Пустой результат",
        "es": "Resultado vacío",
        "uk": "Порожній результат",
    },
    "sponsorship_set_days": {
        "uk": "Тепер виберіть кількість днів, які хочете рекламуватися (відлік днів почнеться з дня оплати + зміщення від уже зайнятих днів).",
        "uz": "Endi siz reklama qilmoqchi bo'lgan kunlar sonini tanlang (kunlar to'langan kundan boshlanadi + ishg'ol qilingan kunlardan ofset).",
        "en": "Now select the number of days you want to advertise (the days will start from the date of payment + offset from the days already occupied).",
        "de": "Wählen Sie nun die Anzahl der Tage aus, die Sie inserieren möchten (die Tage beginnen mit dem Zahlungsdatum + Verrechnung mit den bereits belegten Tagen).",
        "it": "Ora seleziona il numero di giorni che vuoi pubblicizzare (i giorni inizieranno dalla data di pagamento + offset dai giorni già occupati).",
        "ru": "Теперь выберите количество дней, которые хотите рекламироваться (отсчёт дней начнётся со дня оплаты + смещение от уже занятых дней).",
        "es": "Ahora seleccione la cantidad de días que desea anunciar (los días comenzarán a partir de la fecha de pago + compensación de los días ya ocupados).",
        "id": "Sekarang pilih jumlah hari yang ingin Anda iklankan (hari akan dimulai dari tanggal pembayaran + offset dari hari yang sudah ditempati).",
        "pt": "Agora selecione o número de dias que deseja anunciar (os dias começarão a partir da data do pagamento + compensação dos dias já ocupados).",
    },
    "Just send me a text and I will translate it": {
        "ru": "Просто пришлите мне текст, и я его переведу",
        "pt": "Basta me enviar um texto e eu irei traduzi-lo",
        "it": "Mandami un messaggio e lo traduco",
        "uz": "Menga faqat matn yuboring, men uni tarjima qilaman",
        "de": "Schicken Sie mir einfach einen Text und ich übersetze ihn",
        "es": "Solo envíame un mensaje de texto y lo traduciré.",
        "uk": "Просто надішліть мені текст, і я його перекладу",
        "id": "Kirimkan saja saya teks dan saya akan menerjemahkannya",
    },
    "пишите сюда": map[string]string{
        "it": "scrivere qui",
        "uk": "пишіть сюди",
        "de": "hier schreiben",
        "es": "escriba aqui",
        "ru": "пишите сюда",
        "uz": "shu yerga yozing",
        "en": "write here",
        "id": "tulis disini",
        "pt": "escreva aqui",
    },
    "Далее": {
        "de": "Weiter ▶",
        "es": "Siguiente ▶",
        "it": "Avanti ▶",
        "uk": "Далі ▶",
        "uz": "Keyingi ▶",
        "id": "Selanjutnya",
        "pt": "Próximo ▶",
        "ru": "Далее ▶",
        "en": "Next ▶",
    },
    "Failed to detect the language. Please enter something else": {
        "uz": "Til aniqlanmadi. Iltimos, yana bir narsani kiriting",
        "de": "Die Sprache konnte nicht erkannt werden. Bitte geben Sie etwas anderes ein",
        "ru": "Не удалось определить язык. Пожалуйста, введите что-нибудь еще",
        "es": "No se pudo detectar el idioma. Por favor ingrese algo más",
        "uk": "Не вдалося виявити мову. Будь ласка, введіть щось інше",
        "pt": "Falha ao detectar o idioma. Por favor, insira outra coisa",
        "id": "Gagal mendeteksi bahasa. Silakan masukkan sesuatu yang lain",
        "it": "Impossibile rilevare la lingua. Per favore inserisci qualcos'altro",
    },
    "Translate Language": {
        "id": "Terjemahkan Bahasa",
        "de": "Sprache übersetzen",
        "es": "Traducir idioma",
        "uk": "Мова перекладу",
        "ru": "Язык перевода",
        "pt": "Traduzir idioma",
        "en": "Translate Language",
        "it": "Traduci lingua",
        "uz": "Tilni tarjima qilish",
    },
    "To voice": {
        "uk": "озвучити",
        "it": "esprimere",
        "ru": "Озвучить",
        "es": "a voz",
        "pt": "dar voz",
        "id": "untuk menyuarakan",
        "uz": "ovoz berish",
        "de": "aussprechen",
    },
    "Выберите ваш родной язык": {
        "de": "Wählen Sie Ihre Muttersprache",
        "es": "Elija su lengua materna",
        "pt": "Escolha sua língua nativa",
        "ru": "Выберите ваш родной язык",
        "en": "Choose your native language",
        "id": "Pilih bahasa ibu Anda",
        "it": "Scegli la tua lingua madre",
        "uk": "Виберіть ваш рідну мову",
        "uz": "Ona tilingizni tanlang",
    },
    "Введите целое число без лишних символов": {
        "uz": "Qo'shimcha belgilarsiz butun sonni kiriting",
        "id": "Masukkan bilangan bulat tanpa karakter tambahan",
        "pt": "Insira um número inteiro sem caracteres extras",
        "ru": "Введите целое число без лишних символов",
        "uk": "Введіть ціле число без зайвих символів",
        "de": "Geben Sie eine ganze Zahl ohne zusätzliche Zeichen ein",
        "es": "Ingrese un número entero sin caracteres adicionales",
        "it": "Inserisci un numero intero senza caratteri extra",
        "en": "Enter an integer without extra characters",
    },
    "%s language is not supported": {
        "en": "%s language is not supported",
        "uz": "%s tili qo'llab -quvvatlanmaydi",
        "de": "%s Sprache wird nicht unterstützt",
        "pt": "O idioma %s não é compatível",
        "id": "%s bahasa tidak didukung",
        "it": "%s lingua non è supportata",
        "ru": "%s язык не поддерживается",
        "es": "%s idioma no es compatible",
        "uk": "Мова %s не підтримується",
    },
    "v.": { // verb
        "de": "Verb",
        "es": "verbo",
        "pt": "verbo",
        "id": "kata kerja",
        "en": "verb",
        "it": "verbo",
        "uz": "fe'l",
        "ru": "глагол",
        "uk": "дієслово",
    },
    "infl.": { // verb
        "de": "Verb",
        "es": "verbo",
        "pt": "verbo",
        "id": "kata kerja",
        "en": "verb",
        "it": "verbo",
        "uz": "fe'l",
        "ru": "глагол",
        "uk": "дієслово",
    },
    "n.": { // noun
        "en": "noun",
        "de": "Substantiv",
        "ru": "сущ.",
        "uk": "іменник",
        "id": "kata benda",
        "it": "sostantivo",
        "uz": "ism",
        "es": "sustantivo",
        "pt": "substantivo",
    },
    "nf.": { // noun
        "en": "noun",
        "de": "Substantiv",
        "ru": "сущ.",
        "uk": "іменник",
        "id": "kata benda",
        "it": "sostantivo",
        "uz": "ism",
        "es": "sustantivo",
        "pt": "substantivo",
    },
    "nn.": { // noun
        "en": "noun",
        "de": "Substantiv",
        "ru": "сущ.",
        "uk": "іменник",
        "id": "kata benda",
        "it": "sostantivo",
        "uz": "ism",
        "es": "sustantivo",
        "pt": "substantivo",
    },
    "nm.": { // noun
        "en": "noun",
        "de": "Substantiv",
        "ru": "сущ.",
        "uk": "іменник",
        "id": "kata benda",
        "it": "sostantivo",
        "uz": "ism",
        "es": "sustantivo",
        "pt": "substantivo",
    },
    "adv.": {
        "es": "adverbio",
        "pt": "advérbio",
        "id": "kata keterangan",
        "en": "adverb",
        "it": "avverbio",
        "uz": "olmosh",
        "de": "Adverb",
        "ru": "нар.",
        "uk": "прислівник",
    },
    "conj.": {
        "en": "conjunction",
        "de": "Verbindung",
        "es": "conjunción",
        "id": "konjungsi",
        "it": "congiunzione",
        "uz": "birikma",
        "ru": "союз",
        "uk": "сполучення",
        "pt": "conjunção",
    },
    "pron.": {
        "it": "pronome",
        "uk": "займенник",
        "pt": "pronome",
        "id": "kata ganti",
        "en": "pronoun",
        "uz": "olmosh",
        "de": "Pronomen",
        "ru": "местоим.",
        "es": "pronombre",
    },
    "adj.": {
        "en": "adjective",
        "de": "Adjektiv",
        "es": "adjetivo",
        "id": "kata sifat",
        "it": "aggettivo",
        "uz": "sifat",
        "ru": "прил.",
        "uk": "прикметник",
        "pt": "adjetivo",
    },
    "Dictionary": {
        "en": "Dictionary",
        "it": "Dizionario",
        "uk": "Словник",
        "id": "Kamus",
        "uz": "Lug'at",
        "de": "Wörterbuch",
        "ru": "Словарь",
        "es": "Diccionario",
        "pt": "Dicionário",
    },
    "To voice source text": {
        "en": "To voice source",
        "it": "Voce del testo originale",
        "pt": "Soar o texto original",
        "uz": "Manba matnini tarjima qiling",
        "de": "Originaltext vortragen",
        "ru": "Озвучить исходник",
        "es": "Expresar el texto original",
        "uk": "Озвучити вихідний текст",
        "id": "Voice the source text",
    },
    "Select the source language of your text if it was not defined correctly": {
        "id": "Pilih bahasa asli teks Anda jika tidak didefinisikan dengan benar",
        "uz": "Agar matn to'g'ri aniqlanmagan bo'lsa, uning asl tilini tanlang",
        "de": "Wählen Sie die Originalsprache Ihres Textes aus, wenn diese nicht richtig definiert wurde",
        "ru": "Выберите исходный язык вашего текста, если он был определен неправильно",
        "es": "Seleccione el idioma original de su texto si no se definió correctamente",
        "en": "Select the source language of your text if it was not defined correctly",
        "it": "Seleziona la lingua originale del tuo testo se non è stata definita correttamente",
        "uk": "Виберіть вихідний мову вашого тексту, якщо він був визначений неправильно",
        "pt": "Selecione o idioma original do seu texto se não foi definido corretamente",
    },
    "Welcome. We are glad that you are with us again. ✋": {
        "en": "Welcome. We are glad that you are with us again. ✋",
        "it": "Accoglienza. Siamo lieti che tu sia di nuovo con noi. ✋",
        "uz": "Xush kelibsiz. Siz yana biz bilan ekanligingizdan xursandmiz. ✋",
        "ru": "Welcome. We are glad that you are with us again. ✋",
        "uk": "Welcome. We are glad that you are with us again. ✋",
        "pt": "Receber. Estamos felizes por você estar conosco novamente. ✋",
        "de": "Willkommen. Wir freuen uns, dass Sie wieder bei uns sind. ✋",
        "es": "Bienvenido. Nos alegra que vuelva a estar con nosotros. ✋",
        "id": "Selamat datang. Kami senang Anda bersama kami lagi. ✋",
    },
    "The original text language and the target language are the same, please set different": {
        "en": "The original text language and the target language are the same, please set different",
        "uz": "Asl matn va maqsadli til bir xil, iltimos, boshqasini o'rnating",
        "pt": "O idioma do texto original e o idioma de chegada são os mesmos, por favor, defina diferentes",
        "it": "La lingua del testo originale e la lingua di destinazione sono le stesse, impostane una diversa",
        "de": "Die Originaltextsprache und die Zielsprache sind gleich, bitte unterschiedlich einstellen",
        "ru": "Исходный язык текста и язык перевода одинаковы, установите разные",
        "es": "El idioma del texto original y el idioma de destino son los mismos, establezca diferentes",
        "uk": "Вхідна мова тексту і мова перекладу однакові, встановіть різні",
        "id": "Bahasa teks asli dan bahasa target sama, harap atur berbeda",
    },
    "Examples": {
        "en": "Examples",
        "it": "Esempi",
        "de": "Beispiele",
        "pt": "Exemplos",
        "uz": "Misollar",
        "ru": "Примеры",
        "es": "Ejemplos de",
        "uk": "Приклади",
        "id": "Contoh",
    },
    "Meaning": {
        "en": "Meaning",
        "uz": "Ma'nosi",
        "de": "Bedeutung",
        "es": "Sentido",
        "uk": "Значення",
        "id": "Arti",
        "it": "Significato",
        "ru": "Значение",
        "pt": "Significado",
    },
    "Translations": {
        "es": "Traducciones",
        "uk": "Переклади",
        "pt": "Traduções",
        "en": "Translations",
        "it": "Traduzioni",
        "uz": "Tarjimalar",
        "de": "Übersetzungen",
        "ru": "Переводы",
        "id": "Terjemahan",
    },
    "Try built-in mode": {
        "uz": "O'rnatilgan rejimni sinab ko'ring",
        "uk": "Спробуйте вбудований режим",
        "pt": "Experimente o modo integrado",
        "id": "Coba mode bawaan",
        "es": "Prueba el modo integrado",
        "en": "Try built-in mode",
        "it": "Prova la modalità integrata",
        "de": "Probieren Sie den integrierten Modus aus",
        "ru": "Попробуйте встроенный режим",
    },
    "try": {
        "uz": "harakat qilib ko'ring",
        "ru": "пытаться",
        "uk": "спробуйте",
        "pt": "Experimente",
        "it": "Tentativo",
        "de": "Versuchen",
        "es": "tratar",
        "id": "mencoba",
        "en": "try",
    },
    "Did you like the bot?":{
        "uz": "Sizga bot yoqdimi?",
        "de": "Hat dir der Bot gefallen?",
        "es": "¿Te gustó el bot?",
        "uk": "Вам сподобався бот?",
        "en": "Did you like the bot?",
        "it": "Ti è piaciuto il bot?",
        "ru": "Понравился бот?",
        "pt": "Você gostou do bot?",
        "id": "Apakah Anda menyukai botnya?",
    },
    "Donation": {
        "it": "Se vuoi, dona qualche dollaro per lo sviluppo del progetto:\n Numero della carta: 9225-0699-9218-0658",
        "de": "Wenn Sie möchten, spenden Sie ein paar Dollar für die Entwicklung des Projekts:\n Kartennummer: 9225-0699-9218-0658",
        "es": "Si quieres, dona unos dólares para el desarrollo del proyecto:\n Número de tarjeta: 9225-0699-9218-0658",
        "uk": "Якщо хочете, пожертвуйте кілька доларів на розвиток проекту:\n Номер картки: 9225-0699-9218-0658",
        "id": "Jika Anda mau, sumbangkan beberapa dolar untuk pengembangan proyek:\n Nomor kartu: 9225-0699-9218-0658",
        "en": "If you want, donate a few dollars for the development of the project:\nCard number: 9225-0699-9218-0658",
        "uz": "Agar xohlasangiz, loyihani rivojlantirish uchun bir necha dollar xayriya qiling:\n Karta raqami: 9225-0699-9218-0658",
        "ru": "Если хотите, пожертвуйте несколько долларов на развитие проекта:\n Номер карты: 9225-0699-9218-0658",
        "pt": "Se quiser, doe alguns dólares para o desenvolvimento do projeto:\n Número do cartão: 9225-0699-9218-0658",
    },
    "Are you developer?": {
        "it": "Sei uno sviluppatore?",
        "de": "Sind Sie Entwickler?",
        "es": "¿Eres desarrollador?",
        "en": "Are you developer?",
        "uz": "Siz dasturchimisiz?",
        "ru": "Вы разработчик?",
        "uk": "Ви розробник?",
        "pt": "Você é desenvolvedor?",
        "id": "Apakah Anda pengembang?",
    },
    "Yes": {
        "pt": "sim",
        "id": "Ya",
        "it": "sì",
        "uz": "Ha",
        "ru": "да",
        "es": "sí",
        "uk": "Так",
        "en": "Yes",
        "de": "Jawohl",
    },
    "No": {
        "it": "No",
        "uz": "Yo'q",
        "ru": "Нет",
        "es": "No",
        "uk": "Немає",
        "en": "No",
        "de": "Nein",
        "pt": "Não",
        "id": "Tidak",
    },
    "Advice Translo API": {
        "uz": "Vam mumkin byt interesno nadyojnoe API perevodchika, na kotorom rabotaet nash bot: clck.ru/YgruZ",
        "de": "ам может ть интересно надёжное API ереводчика, на котором работает наш от: clck.ru/YgruZ",
        "pt": "Вам может быть интересно надёжное API переводчика, на котором работает наш бот: clck.ru/YgruZ",
        "id": "ам ожет ересно адёжное API ереводчика, а отором аботает аш от: clck.ru/YgruZ",
        "en": "Вам может быть интересно надёжное API переводчика, на котором работает наш бот: clck.ru/YgruZ",
        "it": "ам ожет ть интересно надёжное API переводчика, на котором работает наш от: clck.ru/YgruZ",
        "ru": "Вам может быть интересно надёжное API переводчика, на котором работает наш бот: clck.ru/YgruZ",
        "es": "Вам может быть интересно надёжное API переводчика, на котором работает наш бот: clck.ru/YgruZ",
        "uk": "Вам може бути цікаво надтожний API-переводчик, на якому працює наш бот: clck.ru/YgruZ",
    },
    "Самостоятельно укажите язык вашего текста, если он был определен неправильно": {
        "de": "Geben Sie die Sprache Ihres Textes selbst an, wenn er falsch definiert wurde",
        "es": "Indique usted mismo el idioma de su texto si se definió incorrectamente",
        "uz": "Agar matn noto'g'ri ta'riflangan bo'lsa, uning tilini o'zingiz ko'rsating",
        "pt": "Indique você mesmo o idioma do seu texto, caso tenha sido definido incorretamente",
        "en": "Indicate the language of your text yourself if it was defined incorrectly",
        "uk": "Самостійно вкажіть мову вашого тексту, якщо вона була визначена неправильно",
        "id": "Tunjukkan bahasa teks Anda sendiri jika itu salah didefinisikan",
        "it": "Indica tu stesso la lingua del tuo testo se è stato definito in modo errato",
        "ru": "Самостоятельно укажите язык вашего текста, если он был определен неправильно",
    },
    // ----- to lang ----- //
    "Сейчас бот переводит на <b>%s</b>. Выберите язык, на который хотите переводить": {
        "id": "Bot saat ini sedang menerjemahkan ke <b>% s</b> . Pilih bahasa yang ingin Anda terjemahkan",
        "it": "Il bot sta attualmente traducendo in <b>%s</b> . Seleziona la lingua che vuoi tradurre",
        "en": "The bot is currently translating to <b>%s</b> . Select the language you want to translate",
        "de": "Der Bot übersetzt derzeit in <b>%s</b> . Wählen Sie die Sprache aus, die Sie übersetzen möchten",
        "uz": "Bot hozirda <b>% s ga</b> tarjima qilinmoqda. Tarjima qilmoqchi bo'lgan tilni tanlang",
        "pt": "O bot está traduzindo para <b>%s</b> . Selecione o idioma que deseja traduzir",
        "ru": "Сейчас бот переводит на <b>%s</b>. Выберите язык, на который хотите переводить",
        "es": "El bot se está traduciendo actualmente a <b>%s</b> . Seleccione el idioma que desea traducir",
        "uk": "Зараз бот перекладає на <b>%s</b> . Виберіть мову, на яку хочете перекладати",
    },
    // ----- my lang ----- //
    "Ваш язык <b>%s</b>. Выберите Ваш язык.": map[string]string{
        "id": "Bahasa Anda adalah <b> %s</b> . Pilih bahasamu.",
        "en": "Your language is <b> %s</b> . Choose your language.",
        "de": "Ihre Sprache ist <b> %s</b> . Wähle deine Sprache.",
        "uk": "Ваша мова <b>%s</b> . Виберіть мову.",
        "it": "La tua lingua è <b> %s</b> . Scegli la tua LINGUA.",
        "pt": "Seu idioma é <b> %s</b> . Escolha seu idioma.",
        "ru": "Ваш язык <b>%s</b>. Выберите Ваш язык.",
        "es": "Tu idioma es <b> %s</b> . Elige tu idioma.",
        "uz": "Tilingiz <b>%s</b> . Tilingizni tanlang.",
    },
}


func localize(text, code string, placeholders ...interface{}) string {
    if trigger, ok := translations[text]; ok { // Текст подходит под варианты
        if result, ok := trigger[code]; ok {
            return fmt.Sprintf(result, placeholders...)
        }
    }
   return fmt.Sprintf(text, placeholders...)
}

func command(intent string) []string {
    v, ok := commandTranslations[strings.ToLower(intent)]
    if !ok {
        return []string{}
    }
    return v
}