name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /home/arman/translobot
          sudo git pull origin main
          export PATH=$PATH:/usr/local/go/bin
          go build .
          systemctl restart translobot
